version: 0.2

env:
  variables:
    IMAGE_NAME: "latest"
    ECR_URL: "should be passing in from the build"

phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker build -t $IMAGE_NAME:latest .
      - docker tag $IMAGE_NAME:latest $ECR_URL:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push $ECR_URL:latest
